"""Initial migration with correct schema

Revision ID: e19032b9e9fd
Revises: 
Create Date: 2025-02-23 20:42:09.595086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19032b9e9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transaction')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('family_name')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')
        batch_op.drop_column('house_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('family_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))

    op.create_table('bank_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('narration', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payee', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
